let facials_element = [
  'doc',
  'Price',
  'Skin Type',
  'Item Form',
  'Finish',
  'Active Ingredient',
  'Main Feature',
  'Ratings',
];
let facials = [
  [
    '1',
    '27000',
    'Sensitive, Troubled',
    'Oil',
    'Sticky',
    'Hyaluronic Acid, Panthenol, Glucoside, Aloe Vera',
    'Soothing, Nutritive',
    '4.8',
  ],
  [
    '7',
    '25000',
    'Combination, Sensitive, Troubled',
    'Watery',
    'Fresh, Cool',
    'Propanediol, Bottleweed Extract, Panthenol',
    'Trouble Care, Hypoallergenic',
    '4.3',
  ],
  [
    '8',
    '32000',
    'Dry, Sensitive, Troubled',
    'Cream',
    'Soft, Fresh',
    'Butylene Glycol, Capric Triglyceride, Vegetable Oil',
    'Soothing, Nutritive',
    '4.9',
  ],
  [
    '9',
    '8000',
    'Normal, Sensitive',
    'Watery',
    'Soft, Cool',
    'Propanediol, Glycerin, Cyclohexyloxane',
    'Wrinkle Improvement',
    '3.2',
  ],
  [
    '10',
    '8000',
    'Oily, Troubled',
    'Cream',
    'Sticky',
    'Butylene Glycol, Apple Water, Olive Oil, Glycerin',
    'Soothing, Trouble Care',
    '3.7',
  ],
];

export { facials_element, facials };
